// constants
export const appConstants = {
  GET_REPO_REQUEST: "GET_REPO_REQUEST",
  GET_REPO_SUCCESS: "GET_REPO_SUCCESS",
  GET_REPO_FAILURE: "GET_REPO_FAILURE",
  ADD_REPO_REQUEST: "ADD_REPO_REQUEST",
  ADD_REPO_SUCCESS: "ADD_REPO_SUCCESS",
  ADD_REPO_FAILURE: "ADD_REPO_FAILURE",
  ADD_REPO: "ADD_REPO"
};
